ldb_test.py: testDumpLoad Add --compact
memtable_as_log_index will ignore WriteOptions::disableWAL and always
write wal, this behavior make ldb load with disable_wal omit flush
memtable, thus blob files will not be generated, thus cause fail:

======================================================================
FAIL: testDumpLoad (__main__.LDBTestCase.testDumpLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/ldb_test.py", line 490, in testDumpLoad
    self.assertTrue(len(blob_files) >= 1)
AssertionError: False is not true
======================================================================

We fix this issue by add --compact to generate blob files.